// ============================================================
// Fika - Duplicate Detector
//
// Detects whether a coding problem already exists inside a
// repository Markdown file using the composite primary key:
//
//   Key = (platform + problemId)
//
// Responsibilities:
//   1. Parse existing Markdown files into problem sections
//   2. Identify if a problem exists using platform + problemId
//   3. Compare solution code to distinguish duplicates vs updates
//   4. Process content safely: Append new, Update changed, Skip identical
//
// ============================================================

import { CodingProblem } from "./types";
import { formatProblemToMarkdown } from "./formatter";

// ----------------------------------------------------------
// Result Interface for Duplicate Processing
// ----------------------------------------------------------
export interface DuplicateCheckResult {
  /**
   * Action taken by the detector:
   *   - "created": Problem was not found; appended to file.
   *   - "updated": Problem existed with different code; replaced entry.
   *   - "skipped": Problem existed with identical code; no change needed.
   */
  action: "created" | "updated" | "skipped";

  /** The final Markdown content to be written back to GitHub */
  content: string;
}

// ----------------------------------------------------------
// Extracted metadata from a Markdown problem block
// ----------------------------------------------------------
export interface ExtractedProblemMeta {
  platform: string;
  problemId: string;
  code: string;
}

// ----------------------------------------------------------
// Helper: Parse metadata from a single Markdown problem block
// ----------------------------------------------------------
// Markdown structure generated by formatter.ts:
//
//   ## 1. Two Sum
//   - **Platform**: LeetCode
//   - **Problem ID**: 1
//   ...
//   ### Solution
//   ```python
//   def twoSum(): ...
//   ```
// ----------------------------------------------------------
export function extractProblemMeta(
  blockMarkdown: string
): ExtractedProblemMeta | null {
  // Extract Platform using regex
  const platformMatch = blockMarkdown.match(
    /-\s*\*\*Platform\*\*:\s*([^\r\n]+)/i
  );
  // Extract Problem ID using regex
  const idMatch = blockMarkdown.match(
    /-\s*\*\*Problem ID\*\*:\s*([^\r\n]+)/i
  );

  if (!platformMatch || !idMatch) {
    return null;
  }

  const platform = platformMatch[1].trim();
  const problemId = idMatch[1].trim();

  // Extract solution code inside standard Markdown code fence ``` ... ```
  let code = "";
  const codeMatch = blockMarkdown.match(/```(?:\w+)?\r?\n([\s\S]*?)\r?\n```/);
  if (codeMatch) {
    code = codeMatch[1].trim();
  }

  return {
    platform: platform,
    problemId: problemId,
    code: code,
  };
}

// ----------------------------------------------------------
// Helper: Split a multi-problem Markdown file into sections
// ----------------------------------------------------------
// Problems in a Markdown file are separated by `\n---` or `\n\n---`.
// ----------------------------------------------------------
export function splitMarkdownIntoSections(markdownContent: string): string[] {
  if (!markdownContent || markdownContent.trim() === "") {
    return [];
  }

  // Split by horizontal rule separators (---) surrounded by newlines
  const rawSections = markdownContent.split(/(?:^|\n)\s*---\s*(?=\n|$)/);

  return rawSections
    .map(function (section) {
      return section.trim();
    })
    .filter(function (section) {
      return section.length > 0;
    });
}

// ----------------------------------------------------------
// Core Function: Process duplicate detection and content update
// ----------------------------------------------------------
// Given existing file Markdown and a new CodingProblem:
//   1. Parses existing file into sections
//   2. Searches for a section with matching (platform, problemId)
//   3. If NOT found: Appends new problem ("created")
//   4. If found with SAME code: Returns existing content ("skipped")
//   5. If found with DIFFERENT code: Replaces section ("updated")
// ----------------------------------------------------------
export function processDuplicateDetection(
  existingMarkdown: string,
  problem: CodingProblem
): DuplicateCheckResult {
  const newProblemMarkdown = formatProblemToMarkdown(problem);

  // If the existing file is completely empty, it's a new file
  if (!existingMarkdown || existingMarkdown.trim() === "") {
    return {
      action: "created",
      content: newProblemMarkdown,
    };
  }

  // Parse existing content into individual problem sections
  const sections = splitMarkdownIntoSections(existingMarkdown);

  let existingIndex = -1;
  let existingCode = "";

  // Search sections for matching composite key (platform + problemId)
  for (let i = 0; i < sections.length; i++) {
    const meta = extractProblemMeta(sections[i]);
    if (
      meta &&
      meta.platform.toLowerCase() === problem.platform.toLowerCase() &&
      meta.problemId.toString().trim() === problem.problemId.toString().trim()
    ) {
      existingIndex = i;
      existingCode = meta.code;
      break;
    }
  }

  // Case 1: Problem does not exist in the file -> Append as new
  if (existingIndex === -1) {
    sections.push(newProblemMarkdown);
    return {
      action: "created",
      content: sections.join("\n\n---\n\n"),
    };
  }

  // Case 2: Problem exists -> Compare solution code (normalized)
  const normalizedExistingCode = existingCode.trim().replace(/\r\n/g, "\n");
  const normalizedNewCode = problem.code.trim().replace(/\r\n/g, "\n");

  if (normalizedExistingCode === normalizedNewCode) {
    // Substantially identical code -> Skip writing to GitHub
    return {
      action: "skipped",
      content: existingMarkdown,
    };
  }

  // Case 3: Solution code has changed -> Replace existing section in-place
  sections[existingIndex] = newProblemMarkdown;

  return {
    action: "updated",
    content: sections.join("\n\n---\n\n"),
  };
}
